### ISSUE TITLE
Q: Dataset available?

### ISSUE THREAD

**Issue by senden9** [darryl-snow/perfect-cookie#1]
Hi!

You wrote:
> If there are any Math geniuses who want to help out, right now I'm just using linear equations in the calculations, but they don't exactly fit the model from my data...

I am no math genius but I want to try to find a better model. Is your data set available somewhere? I just found the finished equations at `utilities.js`.

**Comment by snowman-repos** [comment]
@senden9 here you go https://docs.google.com/spreadsheets/d/11CHQdnzdXWd4IrPeGjkeJ9eAeKHjqewL4_KP2lxMdAk/edit?usp=sharing

thanks for taking an interest!
