### ISSUE TITLE
Provide optional imperial volume units

### ISSUE THREAD

**Issue by mholt** [darryl-snow/perfect-cookie#2]
Fun website, thank you for sharing it!

I know that metric weights are superior for baking, buuuut a lot of homes in North America don't have scales or use weight measures for baking (mine included, for the time being). Typically you'll only find them in professional or "serious" kitchens around here.

It'd be great if the site could convert the metric weights to imperial volumes (teaspoon, tablespoon, cup, etc.) for the vast majority of American households.

**Comment by snowman-repos** [comment]
Hi Matt thanks for the feedback! This was heavily requested so I've done by best to add a unit switcher - not sure whether the cups used to measure things typically have a scale on the site, otherwise fractional amounts might be tricky...

**Comment by mholt** [comment]
Thanks! Yeah it's not a perfect method but fractions are as good as it'll get. :)
